### PR TITLE
Fix find_by fails over associations

### PR DESCRIPTION
**Pull request by a2ikm**
`AR::Relation#to_a` is bypassed since Rails 5.0. 
https://github.com/rails/rails/commit/cdd45fa09d76f7c16ccbb6682e672a44f82174a0

This PR replaces it with `AR::Relation#load` which is more lower fetching API.
And this method is used other querying methods `find`, `first`, and so. So we can remove them from `SHARDED_MERHODS`.

Note that this PR is based on #28. So I will rebase this after that PR is merged. This is why I put WIP on the title. Sorry for your inconvenience for a while.

Update: rebased!

### CODE REVIEW

**Comment by the40san** [comment]
👍 

Override lower API is good idea for performance! It's fine to merge.
@a2ikm Could you rebase?

Thank you.

**Comment by a2ikm** [comment]
@the40san 
Thank you, I rebased 😆

**Comment by the40san** [comment]
👍

**Comment by a2ikm** [comment]
Thank you!

**Pull request merged**
