### PR TITLE
Support Rails 5.1+

### PR DESCRIPTION
**Pull request by a2ikm**
This PR adds Rails 5.1+ supports to Tako by passing existing methods to `sharded_methods`.

Additionally, I introduced matrix testing against recent ActiveRecord versions and CRuby versions with Travis-CI because CircleCI seems not to be good at this. If you know some workarounds, please tell me 🙏 
You can see its result at https://travis-ci.org/a2ikm/tako/builds/377548968

And, I removed specs with dummy apps because I think  it's hard to maintain for new Rails versions. If you think we must have them, please tell me. I think minifying apps like [action_arg's fake_app](https://github.com/asakusarb/action_args/blob/master/test/fake_app.rb) is reasonable.

Thanks!

### CODE REVIEW

**Comment by the40san** [comment]
Perfect! thanks

**Comment by the40san** [comment]
完璧すぎる

**Comment by the40san** [comment]
It will released as 0.4.0!

**Comment by a2ikm** [comment]
Thank you!
ありがとうございます！

**Pull request merged**
